# Generated by Django 5.2.4 on 2025-07-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
    ]
